[package]
name = "bascet-provide"
description = "Bascet provide proc macro"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[lib]
proc-macro = true

[dependencies]
heck = "0.5.0"
paste = "1.0.15"
quote = "1.0.42"
syn = "2.0.110"
