[package]
name = "bascet-core"
description = "Core abstractions used for bascet commands"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
bascet-apply = { path = "../bascet-apply" }
bascet-derive = { path = "../bascet-derive" }
paste = "1.0.15"
rtrb = "0.3.2"
